import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, CircleDot, Cpu, Database, LockKeyhole, Network, Server, ShieldCheck, Terminal, Zap } from "lucide-react";
import { ArchitectureDiagram } from "../components/public/ArchitectureDiagram";
import { Footer } from "../components/public/Footer";
import { ProductPreview } from "../components/public/ProductPreview";
import { PublicCodeBlock } from "../components/public/CodeBlock";
import { Navbar } from "../components/public/Navbar";
import { SectionHeading } from "../components/public/SectionHeading";

const githubUrl = "https://github.com/Hellkryptonium/horizon-ai-runtime";

export default function Home() {
  return <>
    <Head><title>Horizon — Distributed AI Compute</title><meta name="description" content="Horizon is a distributed AI compute platform for deploying and running models across connected machines." /><meta property="og:title" content="Horizon — Distributed AI Compute" /><meta property="og:description" content="Deploy models across connected machines through one clear control plane." /><meta property="og:image" content="/logo.png" /><meta property="og:type" content="website" /></Head>
    <div className="public-site"><Navbar /><main>
      <section className="landing-hero"><div className="hero-grid-bg" /><div className="landing-container hero-content"><div className="hero-copy"><div className="public-eyebrow"><span className="eyebrow-line" /> Distributed AI infrastructure</div><h1>Distributed AI Compute,<br /><span>Powered by Everyone.</span></h1><p>Horizon turns compatible machines into a coordinated compute network for AI inference. One control plane for your hardware, models, and workloads.</p><div className="hero-actions"><Link className="public-button public-button-dark" href="/register">Get started <ArrowRight size={15} /></Link><a className="public-button public-button-outline" href={githubUrl} target="_blank" rel="noreferrer">View on GitHub</a></div><div className="hero-note"><span className="status-dot online" /> Built for trusted, team-controlled workers</div></div><div className="hero-diagram-wrap"><div className="hero-diagram-label">Deployment path <span>HZN / 01</span></div><div className="hero-flow"><div className="flow-node"><Terminal size={16} /><span>Developer</span><small>API request</small></div><div className="flow-connector"><span /><i /></div><div className="flow-node flow-node-highlight"><Network size={17} /><span>Control Plane</span><small>Route · observe</small></div><div className="flow-connector"><span /><i /></div><div className="flow-workers"><div className="flow-worker-heading"><span>Connected compute</span><small>3 nodes · 2 online</small></div><div className="flow-worker-list"><div><span className="status-dot online" /> mac-01</div><div><span className="status-dot online" /> windows-01</div><div><span className="status-dot offline" /> node-03</div></div></div><div className="flow-connector"><span /><i /></div><div className="flow-node flow-node-runtime"><Cpu size={16} /><span>Model runtime</span><small>Ollama · qwen2.5:3b</small></div><div className="flow-inference"><span className="status-dot online" /> Inference ready</div></div></div></div></section>
      <section className="preview-section" id="product"><div className="landing-container"><div className="preview-intro"><div><div className="public-eyebrow">The control plane</div><h2>Operate compute,<br />not a collection of machines.</h2></div><p>See workers, deployments, model runtimes, and health in one focused workspace. The preview below uses demonstration configuration based on Horizon's current MVP concepts.</p></div><ProductPreview /></div></section>
      <section className="public-section section-light"><div className="landing-container two-column"><SectionHeading eyebrow="What is Horizon?" title="A control layer for fragmented compute.">AI developers often have hardware in several places: personal workstations, lab machines, development PCs, and unused CPU or GPU capacity. Horizon gives that hardware one operational boundary for inference.</SectionHeading><div className="statement-list"><div><span>01</span><strong>Compatible machines</strong><p>Different operating systems, architectures, and resource profiles.</p></div><div><span>02</span><strong>One control plane</strong><p>Register hardware, target deployments, and observe runtime state.</p></div><div><span>03</span><strong>Trusted by design</strong><p>The current MVP is intended for machines you own or explicitly control.</p></div></div></div></section>
      <section className="public-section problem-section"><div className="landing-container"><SectionHeading eyebrow="The problem" title="AI workloads need somewhere to run." align="center"><span>Cloud GPU infrastructure can be expensive. Personal hardware is often underused. Heterogeneous machines are difficult to operate consistently.</span></SectionHeading><div className="problem-grid"><div><span className="problem-index">01</span><h3>Compute is fragmented</h3><p>Resources live across laptops, workstations, and lab machines with different capabilities.</p></div><div><span className="problem-index">02</span><h3>Operations are scattered</h3><p>Model runtime state, hardware health, and deployment configuration should not live in separate scripts.</p></div><div><span className="problem-index">03</span><h3>Cloud is not always the answer</h3><p>For trusted teams and local workflows, existing hardware can be the practical starting point.</p></div></div></div></section>
      <section className="public-section" id="how-it-works"><div className="landing-container"><SectionHeading eyebrow="How it works" title="A small, explicit path from machine to inference." /><div className="steps-grid"><div><span>01</span><h3>Connect compute</h3><p>Install and run the Horizon Worker Agent on a compatible machine.</p></div><div><span>02</span><h3>Register hardware</h3><p>The worker reports hardware and availability to the Control Plane.</p></div><div><span>03</span><h3>Deploy a model</h3><p>Choose a model and target compatible compute for the workload.</p></div><div><span>04</span><h3>Run inference</h3><p>The model runtime serves requests on the selected worker.</p></div><div><span>05</span><h3>Observe state</h3><p>Track worker status, deployment state, and runtime health.</p></div></div></div></section>
      <section className="network-section"><div className="landing-container network-layout"><div><div className="public-eyebrow">Compute network</div><h2>Different machines.<br />One operational view.</h2><p>Horizon is designed around heterogeneous, trusted compute. Hardware stays where it is; the Control Plane provides the shared language for managing it.</p><div className="network-points"><div><Check size={15} /> Resource-aware worker metadata</div><div><Check size={15} /> One deployment targets one worker</div><div><Check size={15} /> Runtime health before serving</div></div></div><div className="network-map"><div className="map-control"><span className="map-pulse" /> Control Plane <small>central state</small></div><div className="map-lines"><i /><i /><i /></div><div className="map-nodes"><div><span className="node-circle mac">M</span><strong>mac-01</strong><small>Apple Silicon · online</small></div><div><span className="node-circle windows">W</span><strong>windows-01</strong><small>RTX 3050 · online</small></div><div><span className="node-circle linux">L</span><strong>node-03</strong><small>CPU · offline</small></div></div><div className="map-legend"><span><CircleDot size={13} /> Worker connection</span><span><Zap size={13} /> Runtime state</span></div></div></div></section>
      <section className="public-section developer-section"><div className="landing-container developer-layout"><div><div className="public-eyebrow">Developer workflow</div><h2>Build against infrastructure.</h2><p>Horizon is built to make the control plane the interface. Configure workloads, inspect deployments, and integrate through clear HTTP APIs.</p><Link className="text-arrow" href="/developer">Read the developer docs <ArrowRight size={15} /></Link></div><PublicCodeBlock>{"GET /api/models\n\nPOST /api/deployments\n{\n  \"modelId\": \"...\",\n  \"workerId\": \"...\"\n}"}</PublicCodeBlock></div></section>
      <section className="public-section hardware-section"><div className="landing-container"><SectionHeading eyebrow="Heterogeneous by nature" title="Your machines do not need to look alike.">The current MVP focuses on trusted, team-controlled hardware. Support is shaped around what the worker can report and what the runtime can use.</SectionHeading><div className="hardware-grid"><div><div className="hardware-icon"><Cpu size={18} /></div><span>macOS</span><strong>Apple Silicon</strong><small>Architecture-aware resources</small></div><div><div className="hardware-icon"><Server size={18} /></div><span>Windows</span><strong>NVIDIA GPU</strong><small>GPU and VRAM metadata</small></div><div><div className="hardware-icon"><Database size={18} /></div><span>Linux</span><strong>CPU / GPU</strong><small>Platform support evolves with the agent</small></div></div></div></section>
      <section className="public-section trust-section"><div className="landing-container trust-layout"><SectionHeading eyebrow="Built with boundaries" title="Infrastructure is also about what stays separate." /><div className="trust-grid"><div><ShieldCheck size={19} /><h3>Workers do not touch PostgreSQL</h3><p>Worker communication goes through the Control Plane. Database access remains a control-plane concern.</p></div><div><LockKeyhole size={19} /><h3>Structured commands</h3><p>The system is designed around explicit deployment and runtime messages rather than arbitrary shell access.</p></div><div><Server size={19} /><h3>Metadata stays distinct</h3><p>Model metadata and configuration are separate from model weights and local runtime state.</p></div></div></div></section>
      <section className="public-section use-cases"><div className="landing-container"><SectionHeading eyebrow="Where it fits" title="A practical starting point for local infrastructure." /><div className="use-case-grid"><div><span>Personal infrastructure</span><p>Use available hardware for local model serving and development workflows.</p></div><div><span>Research</span><p>Coordinate compatible machines across a research environment.</p></div><div><span>Developer labs</span><p>Pool trusted hardware without immediately renting more cloud capacity.</p></div><div><span>Small teams</span><p>Expose internal compute through one operational control plane.</p></div></div></div></section>
      <section className="architecture-section"><div className="landing-container architecture-layout"><div><div className="public-eyebrow">System architecture</div><h2>Keep the boundaries clear.</h2><p>Workers communicate with the Control Plane. PostgreSQL remains behind it. The deployment path is explicit from request to runtime.</p></div><ArchitectureDiagram /></div></section>
      <section className="final-cta"><div className="landing-container"><div className="final-cta-mark"><Image src="/logo.png" width={30} height={30} alt="" /></div><div className="public-eyebrow">Start with the machines you have</div><h2>Your machines are compute.</h2><p>Connect compatible hardware, deploy models, and build on top of a distributed AI runtime.</p><div className="hero-actions"><Link className="public-button public-button-dark" href="/register">Get started <ArrowRight size={15} /></Link><a className="public-button public-button-outline" href={githubUrl} target="_blank" rel="noreferrer">GitHub</a></div></div></section>
    </main><Footer /></div>
  </>;
}
