import Link from "next/link";
import { useForm } from "react-hook-form";
import { useRouter } from "next/router";
import { useQueryClient } from "@tanstack/react-query";
import { ApiError } from "../lib/api/client";
import { useLoginMutation } from "../lib/query";

type LoginForm = { email: string; password: string };
export default function Login() { const router = useRouter(); const queryClient = useQueryClient(); const login = useLoginMutation(); const { register, handleSubmit, setError, formState: { errors } } = useForm<LoginForm>(); const submit = async (values: LoginForm) => { try { await login.mutateAsync(values); await queryClient.invalidateQueries({ queryKey: ["current-user"] }); void router.push("/dashboard"); } catch (error) { setError("root", { message: error instanceof ApiError && error.status === 401 ? "Invalid email or password." : "Unable to sign in right now." }); } }; return <div className="public-shell"><section className="auth-card"><div className="auth-brand"><span className="brand-mark">H</span> Horizon</div><h1>Welcome back</h1><p>Sign in to manage your Horizon infrastructure.</p><form className="auth-form" onSubmit={handleSubmit(submit)}><div><label className="form-label" htmlFor="email">Email</label><input id="email" className="input" type="email" placeholder="you@example.com" {...register("email", { required: "Email is required" })} />{errors.email && <div className="form-error">{errors.email.message}</div>}</div><div><label className="form-label" htmlFor="password">Password</label><input id="password" className="input" type="password" placeholder="••••••••" {...register("password", { required: "Password is required" })} />{errors.password && <div className="form-error">{errors.password.message}</div>}</div>{errors.root && <div className="form-error">{errors.root.message}</div>}<button className="button primary" disabled={login.isPending}>{login.isPending ? "Signing in..." : "Sign in"}</button></form><div className="auth-footer">New to Horizon? <Link href="/register">Create an account</Link></div></section></div>; }
