import Link from "next/link";
import { useForm } from "react-hook-form";
import { useRouter } from "next/router";
import { useQueryClient } from "@tanstack/react-query";
import { ApiError } from "../lib/api/client";
import { useRegisterMutation } from "../lib/query";

type RegisterForm = { name: string; email: string; password: string; confirmPassword: string };
export default function Register() { const router = useRouter(); const queryClient = useQueryClient(); const registerUser = useRegisterMutation(); const { register, handleSubmit, setError, watch, formState: { errors } } = useForm<RegisterForm>(); const submit = async (values: RegisterForm) => { if (values.password !== values.confirmPassword) { setError("confirmPassword", { message: "Passwords do not match" }); return; } try { await registerUser.mutateAsync({ name: values.name, email: values.email, password: values.password }); await queryClient.invalidateQueries({ queryKey: ["current-user"] }); void router.push("/dashboard"); } catch (error) { setError("root", { message: error instanceof ApiError && error.status === 409 ? "Unable to create account with those details." : "Unable to create your account right now." }); } }; return <div className="public-shell"><section className="auth-card"><div className="auth-brand"><span className="brand-mark">H</span> Horizon</div><h1>Create your account</h1><p>Start deploying workloads on your own hardware.</p><form className="auth-form" onSubmit={handleSubmit(submit)}><div><label className="form-label" htmlFor="name">Name</label><input id="name" className="input" placeholder="Your name" {...register("name", { required: "Name is required" })} />{errors.name && <div className="form-error">{errors.name.message}</div>}</div><div><label className="form-label" htmlFor="email">Email</label><input id="email" className="input" type="email" placeholder="you@example.com" {...register("email", { required: "Email is required" })} />{errors.email && <div className="form-error">{errors.email.message}</div>}</div><div><label className="form-label" htmlFor="password">Password</label><input id="password" className="input" type="password" placeholder="••••••••" {...register("password", { required: "Password is required", minLength: { value: 8, message: "Use at least 8 characters" } })} />{errors.password && <div className="form-error">{errors.password.message}</div>}</div><div><label className="form-label" htmlFor="confirmPassword">Confirm password</label><input id="confirmPassword" className="input" type="password" placeholder="••••••••" {...register("confirmPassword", { required: "Confirm your password", validate: (value) => value === watch("password") || "Passwords do not match" })} />{errors.confirmPassword && <div className="form-error">{errors.confirmPassword.message}</div>}</div>{errors.root && <div className="form-error">{errors.root.message}</div>}<button className="button primary" disabled={registerUser.isPending}>{registerUser.isPending ? "Creating account..." : "Create account"}</button></form><div className="auth-footer">Already have an account? <Link href="/login">Sign in</Link></div></section></div>; }
